### PR TITLE
Expand examples

### PR DESCRIPTION
**Pull request by elbeejay**
Expand documentation examples to:

- provide additional detail about the datasets
- provide examples of accessing the data and visualizing the data

### CODE REVIEW

**Comment by elbeejay** [comment]
Oh and once the files are available it'd be cool to replace the examples with `requests.get()` calls to also show how to retrieve the netCDF files and then manipulate them... we'll have to see if this is possible down the road.

**Comment by g4brielvs** [comment]
> Oh and once the files are available it'd be cool to replace the examples with `requests.get()` calls to also show how to retrieve the netCDF files and then manipulate them... we'll have to see if this is possible down the road.

You read my mind! Depending on how the AWS bucket is set up, it could be possible to [read and write Xarray datasets directly from/to cloud storage buckets](https://docs.xarray.dev/en/stable/user-guide/io.html#cloud-storage-buckets).

**Comment by g4brielvs** [comment]
@elbeejay Thank you for initiating this pull request! It looks good to me, but the CCKP team may inform better. Updating the documentation and looping in the CCKP team for further input sounds like a solid plan.

**Comment by elbeejay** [comment]
> @elbeejay Thank you for initiating this pull request! It looks good to me, but the CCKP team may inform better. Updating the documentation and looping in the CCKP team for further input sounds like a solid plan.

This sounds good. I've expanded the examples so maybe we can merge and then ask the CCKP team for further feedback. Feel free to merge if you think it looks good.

**Review by g4brielvs — APPROVED** [review]

**Pull request merged**
